{
  # -------- Data Paths -------- #
  
  'train-data-paths': [
    '/data/metagenomics/pretraining_data_metagenomics/data_metagenomics_train_text_CharLevelTokenizer_document',
    '/data/gtdb_v220/gtdb_v220_imgpr_merged_data/data_gtdb_imgpr_train_text_CharLevelTokenizer_document',
    '/data/imgvr_untagged/imgvr_untagged_data/data_imgvr_train_text_CharLevelTokenizer_document',
    '/data/ncrna/pretraining_data_ncrna/data_ncrna_train_text_CharLevelTokenizer_document',
    '/data/mrna/pretraining_data_mrna/data_mrna_train_text_CharLevelTokenizer_document',
    '/data/euk_windows/stitched_transcripts/pretraining_data_stiched_mrna/data_mrna_stitch_train_text_CharLevelTokenizer_document',
    '/data/euk_windows/windows_split/5kb_windows_lowercase/5kb_windows_lowercase_pretraining_data/windows_5kb_train_text_CharLevelTokenizer_document',
    '/data/promoters/pretraining_data_promoters/data_promoters_train_text_CharLevelTokenizer_document',
    '/data/organelle/pretraining_data_organelle/data_organelle_train_text_CharLevelTokenizer_document',
  ],
  
  'valid-data-paths': [
    '/data/metagenomics/pretraining_data_metagenomics/data_metagenomics_valid_text_CharLevelTokenizer_document',
    '/data/gtdb_v220/gtdb_v220_imgpr_merged_data/data_gtdb_imgpr_valid_text_CharLevelTokenizer_document',
    '/data/imgvr_untagged/imgvr_untagged_data/data_imgvr_valid_text_CharLevelTokenizer_document',
    '/data/ncrna/pretraining_data_ncrna/data_ncrna_valid_text_CharLevelTokenizer_document',
    '/data/mrna/pretraining_data_mrna/data_mrna_valid_text_CharLevelTokenizer_document',
    '/data/euk_windows/stitched_transcripts/pretraining_data_stiched_mrna/data_mrna_stitch_valid_text_CharLevelTokenizer_document',
    '/data/euk_windows/windows_split/5kb_windows_lowercase/5kb_windows_lowercase_pretraining_data/windows_5kb_valid_text_CharLevelTokenizer_document',
    '/data/promoters/pretraining_data_promoters/data_promoters_valid_text_CharLevelTokenizer_document',
    '/data/organelle/pretraining_data_organelle/data_organelle_valid_text_CharLevelTokenizer_document',
  ],

  'test-data-paths': [
    '/data/metagenomics/pretraining_data_metagenomics/data_metagenomics_test_text_CharLevelTokenizer_document',
    '/data/gtdb_v220/gtdb_v220_imgpr_merged_data/data_gtdb_imgpr_test_text_CharLevelTokenizer_document',
    '/data/imgvr_untagged/imgvr_untagged_data/data_imgvr_test_text_CharLevelTokenizer_document',
    '/data/ncrna/pretraining_data_ncrna/data_ncrna_test_text_CharLevelTokenizer_document',
    '/data/mrna/pretraining_data_mrna/data_mrna_test_text_CharLevelTokenizer_document',
    '/data/euk_windows/stitched_transcripts/pretraining_data_stiched_mrna/data_mrna_stitch_test_text_CharLevelTokenizer_document',
    '/data/euk_windows/windows_split/5kb_windows_lowercase/5kb_windows_lowercase_pretraining_data/windows_5kb_test_text_CharLevelTokenizer_document',
    '/data/promoters/pretraining_data_promoters/data_promoters_test_text_CharLevelTokenizer_document',
    '/data/organelle/pretraining_data_organelle/data_organelle_test_text_CharLevelTokenizer_document',
  ],

  # -------- Data Weights -------- #

  'train-data-weights': [
    0.18, 
    0.24, 
    0.03, 
    0.02, 
    0.09, 
    0.09, 
    0.35, 
    0.0003, 
    0.005
  ],
  
  'test-data-weights': [
    0.18, 
    0.24, 
    0.03, 
    0.02, 
    0.09, 
    0.09, 
    0.35, 
    0.0003, 
    0.005
  ],

  'valid-data-weights': [
    0.18, 
    0.24, 
    0.03, 
    0.02, 
    0.09, 
    0.09, 
    0.35, 
    0.0003, 
    0.005
  ],

  'checkpoint_validation_with_forward_pass': False 
}
