{
  "pipe_parallel_size": 2,
  "model_parallel_size": 1,
  "make_vocab_size_divisible_by": 8,

  "num_layers": 32,
  "hidden_size": 4096,
  "num_attention_heads": 32,
  "num_heads": 4096,
    "attention-config": [ 
    [["hyena_se"], 1], [["hyena_mr"], 1], [["hyena"], 2], 
    [["hyena_se"], 1], [["hyena_mr"], 1], [["hyena"], 2], 
    [["hyena_se"], 1], [["hyena_mr"], 1], [["hyena"], 2],  # 12
    [["flash_v2"], 1],
    [["hyena_se"], 1], [["hyena_mr"], 1], [["hyena"], 3],
    [["hyena_se"], 1], [["hyena_mr"], 1], [["hyena"], 2],  # 9
    [["flash_v2"], 1], 
    [["hyena_se"], 1], [["hyena_mr"], 1], [["hyena"], 2], 
    [["hyena_se"], 1], [["hyena_mr"], 1], [["hyena"], 2],  # 8
    [["flash_v2"], 1] ],
  "seq_length": 8192,
  "max_position_embeddings": 8192,
  "hyena_mr_len": 128,  # default is null  
  "log_attn_norms": false,
  "pos_emb": "rotary",
  "rotary_pct": 1,
  "prenorm": true,
  "postnorm": false,
  "pre_mlp_norm": true,  
  "outer_mlp_norm": false,
  "no_weight_tying": false,
  "gpt_j_residual": false,
  "normalize_hyena_filters": false,
  "short-conv-L": 3, 
  "hyena_filter_fast_decay": 0.3,
  "hyena_filter_slow_decay": 1.2,
  "hyena_filter_w": 14, 
  "hyena_filter_cls": "implicit_complex_modal",
  "hyena_filter_order": 16,
  "hyena_filter_wd": 0.,
  "use_fast_heads": false,
  "use_slow_heads": false,
  "use-hyena-filter": true,
  "output_layer_parallelism": "column",
  "bias_dropout_fusion": false,
  "norm": "rmsnorm",
  "rms_norm_epsilon": 1.0e-6,
  "identity_mlp": false,
   "mlp_type": "llama",
   "scaled-upper-triang-masked-softmax-fusion": true,
   "bias-gelu-fusion": false,
   "init_method": "small_init",
   "output_layer_init_method": "wang_init",
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.0003,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8,
     }
   },
   "min_lr": 0.00003,
   "zero_optimization": {
    "stage": 0,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
    "cpu_offload": false
  },
   "train_micro_batch_size_per_gpu": 2,
   "gradient_accumulation_steps": 8,
   "data-impl": "mmap",
   "checkpoint-activations": true,
   "checkpoint-num-layers": 4,
   "partition-activations": true,
   "synchronize-each-layer": true,
   "gradient_clipping": 1.0,
   "weight-decay": 0.1,
   "hidden-dropout": 0.0,
   "attention-dropout": 0.0,
   "precision": "bfloat16",
   "bf16": {
   "enabled": true
    },
   "train-iters": 400_000,
   "lr-decay-iters": 400_000,
   "distributed-backend": "nccl",
   "lr-decay-style": "cosine",
   "warmup": 0.005,
   "checkpoint-factor": 500,
  "extra_save_iters": [4],
   "eval-interval": 100,
   "eval-iters": 20,
   "log-interval": 25,
   "steps_per_print": 25,
   "keep-last-n-checkpoints": 15,
   "wall_clock_breakdown": false,
   "save": "/checkpoint/hielab/etnguyen/checkpoints/evo2/7b_15h_7m_7sc_3a_400k_sc4_same_1worker_16nodes", # change this
   "tokenizer_type": CharLevelTokenizer,   
  #  "iteration": 200,
  #  "use_checkpoint_lr_scheduler": True,
  #  "use_fp8_linears": true,
   "master_port": 29504,
  #  "include": "localhost@localhost:0",
  #  "num_gpus": 1,
  #  "bidirectional": True,
   "materialize_attn_mask": false,  # default false, to save memory
  #  "tie_projection_weights": true,
  "seed": 2223,
    "hyena_se_len": 4,
    "fast_conv_mixer": true,
    "fast_conv_proj": true,
    "use_wandb": true,
    "to_upper": "weighted",
    "lowercase_loss_reweighting": 0.1,  
    "num_workers": 1,
    # "make_gated_mlp_multiple_of": 128,

  # multinode
  "launcher": "pdsh",
  "hostfile": "./hostfile_eric",
  "deepspeed_slurm": false,

  # # resume
  # "iteration": 1500,
  # "load": "/checkpoint/hielab/etnguyen/checkpoints/7b_15h_7m_7sc_3a_120k",
  # "use_checkpoint_lr_scheduler": True,  
}
