# @jeromeku IMPORTANT: Needed for continued pretraining from a 40b checkpoint without interleaving
explicit_filter_num_decay_repeats: 1

# CP Config
use_cp_flash_te: true
te_attn_backend: 'FLASH'
use_cp_ring: false
use_cp_hyena: false

# Checkpointing
# @jeromeku: Corresponds to pretrained checkpoint global_step516000 converted using `tools/40b/zero3/40b_512K_conversion.sh`
# checked by first converting extended zero-3 checkpoint to zero-1 shards using `tools/40b/zero3/convert_zero3.sh` and then comparing original 8K and extended 512K filterstools/40b/zero3/check_extended_filters.py
seq_length: 32768
pos_emb: 'rotary_linear_scaled'
rotary_emb_base: 1000000
rotary_emb_scaling_factor: 4
rotary_pct: 1
max_position_embeddings: 8192

# Training
train-iters: 100
lr-decay-iters: 100

# Per ds evals
eval-interval: 500
eval-iters: 0

# Optimizer and LR Scheduler
optimizer:
  type: 'Adam'
  params:
    lr: 0.00003
    betas: [0.9, 0.95]
    eps: 1.0e-8
min_lr: 0.000003
warmup: 0.05
lr-decay-style: cosine

# Loss
to_upper: normalized_weighted
mask_loss_control_tags: true
lowercase_loss_reweighting: 0.1

# Checkpointing
checkpoint-factor: 200
save_retain_interval: 2000
keep-last-n-checkpoints: 10

# IMPORTANT: needed to stabilize training at 1k+ gpus
disable_gc: true
gc_collect_generation: 2
prealloc_mem: false

# Logging
use_wandb: true
print_mem_alloc_stats: false
log_memory_stats: true
log_memory_alloc_counts: false

# MP / PP config
pipe_parallel_size: 0
model_parallel_size: 8
context_parallel_size: 1
sequence_parallel: true

zero_optimization:
  stage: 3
  prefetch_bucket_size: 500000000
  max_live_parameters: 1000000000
  allgather_partitions: true
  allgather_bucket_size: 500000000
  overlap_comm: true
  reduce_scatter: true
  reduce_bucket_size: 500000000
  contiguous_gradients: true
  cpu_offload: false
  param_persistence_threshold: 0
  sub_group_size: 1000000000000
train_micro_batch_size_per_gpu: 2
gradient_accumulation_steps: 1

# Activation checkpointing - @jeromeku after fp8 / sequence-parallel fix, needed to lower memory pressure / prevent memory thrashing
checkpoint-activations: true
checkpoint-num-layers: 2

# Checkpointing
zero_use_leaf_modules: false
zero_leaf_modules: [ParallelSequenceMixer, ParallelGLU]

zero_use_mics: false
make_vocab_size_divisible_by: 8
num_layers: 50
hidden_size: 8192
num_attention_heads: 64
num_groups_hyena: 8192
num_groups_hyena_medium: 512
num_groups_hyena_short: 512
num_groups_hyena_mlp: 512
operator-config:
  -   -   - flash_te
      - 50
use_cgcg: false
use_cgcg_short: false
use_cgcg_mlp: false

hyena_mr_len: 128  # default is null
log_attn_norms: false
prenorm: true
postnorm: false
pre_mlp_norm: true
outer_mlp_norm: false
no_weight_tying: false
gpt_j_residual: false
normalize_hyena_filters: false
short-conv-L: 3
hyena_filter_fast_decay: 0.3
hyena_filter_slow_decay: 1.2
hyena_filter_w: 14
hyena_filter_cls: implicit_modal
hyena_medium_filter_cls: explicit_single_decay
explicit_filter_decay_preset: weak
hyena_filter_order: 16
hyena_filter_wd: 0.0
use_fast_heads: false
use_slow_heads: false
use-hyena-filter: true
output_layer_parallelism: column
bias_dropout_fusion: false
norm: rmsnorm
rms_norm_epsilon: 1.0e-6
identity_mlp: false
activation: gelu
mlp_type: llama
scaled-upper-triang-masked-softmax-fusion: true
bias-gelu-fusion: false
init_method: small_init
output_layer_init_method: wang_init

data-impl: mmap

partition-activations: false
synchronize-each-layer: false
gradient_clipping: 1.0
weight-decay: 0.1
hidden-dropout: 0.0
attention-dropout: 0.0
precision: bfloat16
bf16:
  enabled: true
distributed-backend: nccl


log-interval: 5
steps_per_print: 5
wall_clock_breakdown: false

tokenizer_type: CharLevelTokenizer # Assuming this is a valid identifier
use_fp8_input_projections: true
use_fp8_output_projections: true
use_fp8_mlp_projections: true
use_fp8_norm: true
checkpoint_strict_load: false
make_gated_mlp_multiple_of: 128
materialize_attn_mask: false  # default false, to save memory
fast_conv_proj: true
hyena_se_len: 7
