{ "train-data-paths": ["/data/gtdb_imgpr/pretraining_data_gtdb_imgpr/data_gtdb_imgpr_train_text_CharLevelTokenizer_document"],
  "test-data-paths": ["/data/gtdb_imgpr/pretraining_data_gtdb_imgpr/data_gtdb_imgpr_test_text_CharLevelTokenizer_document"],
  "valid-data-paths": ["/data/gtdb_imgpr/pretraining_data_gtdb_imgpr/data_gtdb_imgpr_valid_text_CharLevelTokenizer_document"],
  "test-data-weights": [1.],
  "valid-data-weights": [1.],
  "checkpoint_validation_with_forward_pass": False,
}