{
  "pipe_parallel_size": 1,
  "model_parallel_size": 1,
  "make_vocab_size_divisible_by": 8,

  "num_layers": 33,
  "hidden_size": 1280,
  "num_attention_heads": 20,
  "num_heads": 1280,
    "operator-config": [ [["hyena"], 10], [["flash_v2"], 1] , [["hyena"], 10], [["flash_v2"], 1], [["flash_v2"], 10], [["flash_v2"], 1] ],
  "seq_length": 1024,
  "max_position_embeddings": 1024,

  "pos_emb": "rotary",
  "rotary_pct": 1,
  "prenorm": true,
  "postnorm": false,
  "pre_mlp_norm": true,  
  "outer_mlp_norm": false,
  "no_weight_tying": false,
  "gpt_j_residual": false,
  "normalize_hyena_filters": false,
  "short-conv-L": 3, 
  "hyena_filter_fast_decay": 0.3,
  "hyena_filter_slow_decay": 1.2,
  "hyena_filter_w": 14, 
  "hyena_filter_cls": "implicit_real_modal",
  "hyena_filter_order": 16,
  "hyena_filter_wd": 0.,
  "use_fast_heads": false,
  "use_slow_heads": false,
  "use-hyena-filter": true,
  "output_layer_parallelism": "column",
  "bias_dropout_fusion": false,
  "norm": "rmsnorm",
  "rms_norm_epsilon": 1.0e-6,
  "identity_mlp": false,
   "mlp_type": "llama",
   "scaled-upper-triang-masked-softmax-fusion": true,
   "bias-gelu-fusion": false,
   "init_method": "small_init",
   "output_layer_init_method": "wang_init",
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.0004,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8,
     }
   },
   "min_lr": 0.00004,
   "zero_optimization": {
    "stage": 0,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
    "cpu_offload": false
  },
   "train_micro_batch_size_per_gpu": 128, # increase the batch size to 4m 
   "gradient_accumulation_steps": 1,
   "data-impl": "mmap",
   "checkpoint-activations": true,
   "checkpoint-num-layers": 1,
   "partition-activations": true,
   "synchronize-each-layer": true,
   "gradient_clipping": 1.0,
   "weight-decay": 0.1,  # increase the weight decay
   "hidden-dropout": 0.0,
   "attention-dropout": 0.0,
   "precision": "bfloat16",
   "bf16": {
   "enabled": true
    },
   "train-iters": 600_000,
   "lr-decay-iters": 600_000,
   "distributed-backend": "nccl",
   "lr-decay-style": "cosine",
   "warmup": 0.01,
   "checkpoint-factor": 8_000,
   "eval-interval": 1000,
   "eval-iters": 20,
   "log-interval": 200,
   "steps_per_print": 200,
   "keep-last-n-checkpoints": 100,
   "wall_clock_breakdown": false,
  #  "extra_save_iters": [32004],
   "save": "/checkpoint/hielab/etnguyen/protein_striped_hyena_650m_500k_fixed_v3_test", # change this
  #  "load": "/checkpoint/hielab/etnguyen/protein_striped_hyena_650m_500k_fixed_v2", # change this
   "tokenizer_type": CharLevelTokenizer,
   "enforce_sample_length": True,  # sequence packing off
   "pad_mask_loss": True, # ignore 
  # # multinode
  "launcher": "pdsh",
  "hostfile": "./hostfile_uniprot_test",
  "deepspeed_slurm": false,   
  # # resume
  #  "iteration": 32000,
  #  "use_checkpoint_lr_scheduler": True,
  #  "use_fp8_linears": false,
  #  "master_port": 29502,
  #  "include": "localhost@localhost:0",
  #  "num_gpus": 1,
  #  "enforce_sample_length": True, 
  #  "wandb_project": "dna-gen"
}

