{
   "pipe-parallel-size": 1,
   "model-parallel-size": 1,

   ############### model settings
   "num-layers": 12,
   "hidden-size": 768,
   "num-attention-heads": 12,
   "seq-length": 2048,
   "max-position-embeddings": 2048,
   "norm": "layernorm",
   "pos-emb": "rotary",
   "no-weight-tying": true,
   "gpt_j_residual": false,
   "output_layer_parallelism": "column",

   ############## misc optims
   "scaled-upper-triang-masked-softmax-fusion": false,
   "bias-gelu-fusion": false,

   ############### init
   "init_method": "small_init",
   "output_layer_init_method": "wang_init",

   ############## optimizer
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.0006,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8,
     }
   },
   "min_lr": 0.00006,

   ############### sys optims
   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
  },

   ################# batch sizes
   "train_micro_batch_size_per_gpu": 32,
   "data-impl": "mmap",
   "train_batch_size": 256,

   ################# act checkpointing
   "checkpoint-activations": true,
   "checkpoint-num-layers": 1,
   "partition-activations": true,
   "synchronize-each-layer": true,

   ################# regularization
   "gradient_clipping": 1.0,
   "weight-decay": 0.1,
   "hidden-dropout": 0.0,
   "attention-dropout": 0.0,

   ################ precision
   "precision": "bfloat16",
   "bf16": {
   "enabled": true
    },
   
   ################# training
   "train-iters": 30000,
   "lr-decay-iters": 30000,
   "distributed-backend": "nccl",
   "lr-decay-style": "cosine",
   "warmup": 0.05,
   "checkpoint-factor": 10000,
   "eval-interval": 1000,
   "eval-iters": 10,

   ################ logging
   "log-interval": 200,
   "steps_per_print": 200,
   "keep-last-n-checkpoints": 4,
   "wall_clock_breakdown": false,

  ################# networking
  "hostfile": "/mock_path"
}
