{
   "pipe-parallel-size": 1,
   "model-parallel-size": 1,

   ############### model settings
   "num-layers": 24,
   "hidden-size": 896,
   "operator-config": [[["hyena"], 24]],
   "short-conv-L": 4,
   "use-hyena-filter": true,
   "hyena_filter_cls": "modal",
   "hyena_filter_r_min": 0.0,
   "hyena_filter_r_max": 0.001,
   "seq-length": 2048,
   "norm": "layernorm",
   "output_layer_parallelism": "column",
   "identity_mlp": true,
   "pos_emb": None,
   "num_heads": 8, # hidden-size / num_heads unique filters
   "num_attention_heads": 8, # nb: this is only used for mpu with vanilla Hyena, no heads to split

   ############## misc optims
   "scaled-upper-triang-masked-softmax-fusion": false,
   "bias-gelu-fusion": false,

   ############### init
   "init_method": "small_init",
   "output_layer_init_method": "wang_init",

   ############## optimizer
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.0006,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8,
     }
   },
   "min_lr": 0.00006,

   ############### sys optims
   "zero_optimization": {
    "stage": 0,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
  },

   ################# batch sizes
   "train_micro_batch_size_per_gpu": 64,
   "data-impl": "mmap",

   ################# act checkpointing
   "checkpoint-activations": true,
   "checkpoint-num-layers": 1,
   "partition-activations": true,
   "synchronize-each-layer": true,

   ################# regularization
   "gradient_clipping": 1.0,
   "weight-decay": 0.1,
   "hidden-dropout": 0.0,
   "attention-dropout": 0.0,

   ################ precision
   "precision": "bfloat16",
   "bf16": {
   "enabled": true
    },
   
   ################# training
   "train-iters": 400000,
   "lr-decay-iters": 400000,
   "distributed-backend": "nccl",
   "lr-decay-style": "cosine",
   "warmup": 0.01,
   "checkpoint-factor": 10000,
   "eval-interval": 10000,
   "eval-iters": 10,

   ################ logging
   "log-interval": 200,
   "steps_per_print": 200,
   "keep-last-n-checkpoints": 4,
   "wall_clock_breakdown": false,

  ################# networking
  "hostfile": "/mock_path"
}

