{
  "pipe_parallel_size": 1,
  "model_parallel_size": 1,
  "make_vocab_size_divisible_by": 8,

  "num_layers": 4,
  "hidden_size": 64,
  "num_attention_heads": 2,
  "num_heads": 64, 
  "operator-config": [ [["hyena"], 1], [["flash_v2"], 1], [["hyena"], 1], [["flash_v2"], 1] ], 
   "seq_length": 8192,
  "max_position_embeddings": 8192,

  "hyena_filter_cls": "implicit_real_modal",
  "pos_emb": "rotary",
  "rotary_pct": 1,
  "prenorm": true,
  "postnorm": false,
  "pre_mlp_norm": true,  
  "outer_mlp_norm": false,
  "no_weight_tying": false,
  "gpt_j_residual": false,
  "normalize_hyena_filters": false,
  "short-conv-L": 3, 
  "hyena_filter_fast_decay": 0.3,
  "hyena_filter_slow_decay": 1.2,
  "hyena_filter_w": 14, 
  "hyena_filter_order": 16,
  "hyena_filter_wd": 0.,
  "use_fast_heads": false,
  "use_slow_heads": false,
  "use-hyena-filter": true,
  "output_layer_parallelism": "column",
  "bias_dropout_fusion": false,
  "norm": "rmsnorm",
  "rms_norm_epsilon": 1.0e-6,
  "identity_mlp": false,
   "mlp_type": "llama",
   "scaled-upper-triang-masked-softmax-fusion": true,
   "bias-gelu-fusion": false,
   "init_method": "small_init",
   "output_layer_init_method": "wang_init",
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.0003,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8,
     }
   },
   "min_lr": 0.00003,
   "zero_optimization": {
    "stage": 0,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
    "cpu_offload": false
  },
   "train_micro_batch_size_per_gpu": 1,
   "gradient_accumulation_steps": 1,
   "data-impl": "mmap",
   "checkpoint-activations": true,
   "checkpoint-num-layers": 1,
   "partition-activations": true,
   "synchronize-each-layer": true,
   "gradient_clipping": 1.0,
   "weight-decay": 0.1,
   "hidden-dropout": 0.0,
   "attention-dropout": 0.0,
   "precision": "bfloat16",
   "bf16": {
   "enabled": true
    },
   "train-iters": 25000,
   "lr-decay-iters": 25000,
   "distributed-backend": "nccl",
   "lr-decay-style": "cosine",
   "warmup": 0.01,
   "checkpoint-factor": 10000,
   "eval-interval": 5000,
   "eval-iters": 20,
   "log-interval": 500,
   "steps_per_print": 500,
   "keep-last-n-checkpoints": 4,
   "wall_clock_breakdown": false,
   "vocab-file": "/mnt/data/gpt2-vocab.json",
   "merge-file": "/mnt/data/gpt2-merges.txt",
  "data-path": "/mnt/data/enwik8/enwik8_text_GPT2BPE_document",
}

