
{
  "pipe_parallel_size": 1,
  "model_parallel_size": 1,
  "make_vocab_size_divisible_by": 8,

  "num_layers": 32,
  "hidden_size": 5120,
  "num_groups_hyena": 5120,
  "num_groups_hyena_medium": 320,
  "num_groups_hyena_short": 320,
  "num_groups_hyena_mlp": 320,
  "num_attention_heads": 320, 
  # "num_heads": 1024, 
  "operator-config": [ 
    [["hyena_se"], 1], [["hyena_mr"], 1], [["hyena"], 2],
    [["hyena"], 1], [["hyena_se"], 1], [["hyena_mr"], 1], [["hyena"], 1],  # 8
    [["flash_v2"], 1],
    [["hyena_se"], 1], [["hyena_mr"], 1], [["hyena"], 1],
    [["hyena"], 1], [["hyena_se"], 1], [["hyena_mr"], 1], [["hyena"], 1],
    [["hyena_se"], 1], [["hyena_mr"], 1], [["hyena"], 1],  # 10
    [["flash_v2"], 1],
    [["hyena"], 1], [["hyena_se"], 1], [["hyena_mr"], 1], [["hyena"], 1],
    [["hyena_se"], 1], [["hyena_mr"], 1], [["hyena"], 1],
    [["hyena"], 1], [["hyena_se"], 1], [["hyena_mr"], 1], [["hyena"], 1],  #  11
    [["flash_v2"], 1],
    ],
  "seq_length": 8192,
  "max_position_embeddings": 8192,
  "hyena_mr_len": 128,  # default is null
  "log_attn_norms": false,
  "pos_emb": "rotary",
  "rotary_emb_base": 1000000,
  "rotary_pct": 1,
  "prenorm": true,
  "postnorm": false,
  "pre_mlp_norm": true,  
  "outer_mlp_norm": false,
  "no_weight_tying": false,
  "gpt_j_residual": false,
  "normalize_hyena_filters": false,
  "short-conv-L": 3, 
  "hyena_filter_fast_decay": 0.3,
  "hyena_filter_slow_decay": 1.2,
  "hyena_filter_w": 14, 
  "hyena_filter_cls": "implicit_real_modal",
  "hyena_medium_filter_cls": "explicit_single_decay",  
  "explicit_filter_decay_preset": "weak",
  "modal_residue_factors": 5,
  "modal_pole_factors": 1,
  "hyena_filter_order": 32,
  "hyena_filter_wd": 0.,
  "use_fast_heads": false,
  "use_slow_heads": false,
  "use-hyena-filter": true,
  "output_layer_parallelism": "column",
  "bias_dropout_fusion": false,
  "norm": "rmsnorm",
  "rms_norm_epsilon": 1.0e-6,
  "identity_mlp": false,
   "mlp_type": "short_hyena",
   "scaled-upper-triang-masked-softmax-fusion": true,
   "bias-gelu-fusion": false,
   "init_method": "small_init",
   "output_layer_init_method": "wang_init",
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.0003,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8,
     }
   },
   "min_lr": 0.00003,
   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
    "cpu_offload": false
  },
   "train_micro_batch_size_per_gpu": 2,
   "gradient_accumulation_steps": 4,
   "data-impl": "mmap",
   "checkpoint-activations": true,
   "checkpoint-num-layers": 2,
   "partition-activations": true,
   "synchronize-each-layer": false,
   "gradient_clipping": 1.0,
   "weight-decay": 0.1,
   "hidden-dropout": 0.0,
   "attention-dropout": 0.0,
   "precision": "bfloat16",
   "bf16": {
   "enabled": true
    },
   "train-iters": 400000,
   "lr-decay-iters": 400000,
   "distributed-backend": "nccl",
   "lr-decay-style": "cosine",
   "warmup": 0.005,
   "checkpoint-factor": 500,
   "eval-interval": 100,
   "eval-iters": 20,
   "log-interval": 25,
   "steps_per_print": 25,
   "keep-last-n-checkpoints": 2,
   "wall_clock_breakdown": false,
   "save": "/checkpoint/hielab/etnguyen/checkpoints/evo2/7b/7b_13h_8m_8s_3a_hymlp_hd16_irm_esd_param_match_16n_univ", # change this
   "tokenizer_type": CharLevelTokenizer,   
   "use_fp8_linears": true,
   "master_port": 29504,
  #  "include": "localhost@localhost:0",
  #  "num_gpus": 1,
  #  "bidirectional": True,
  "make_gated_mlp_multiple_of": 64,
   "materialize_attn_mask": false,  # default false, to save memory
  "fast_conv_proj": true,   
  "hyena_se_len": 7,
  "use_wandb": true,  
  "to_upper": "weighted",
  "lowercase_loss_reweighting": 0.1,  
  "hyena_mlp_len": 7,  
  "num_workers": 1,

  # multinode
  "launcher": "pdsh",
  "hostfile": "./hostfile_eric",
  "deepspeed_slurm": false,

  # resume
  "checkpoint": {"load_universal": True},
  "iteration": 1000,  # need this to automatically find the path. "4" is an example
  "load": "/checkpoint/hielab/etnguyen/checkpoints/evo2/7b/7b_13h_8m_8s_3a_hymlp_hd16_irm_esd_param_match_4n",  # original non-universal checkpoint path
  "use_checkpoint_lr_scheduler": True,  

}