{
  "pipe_parallel_size": 2,
  "model_parallel_size": 1,
  "make_vocab_size_divisible_by": 8,

  "num_layers": 32,
  "hidden_size": 4096,
  "num_attention_heads": 32,
  "num_heads": 4096,
  "attention-config": [[["hyena"], 8], [["flash_v2"], 1], [["hyena"], 7], [["flash_v2"], 1], [["hyena"], 7], [["flash_v2"], 1], [["hyena"], 7]],
   "seq_length": 8192,
  "max_position_embeddings": 8192,
  "log_attn_norms": false,
  "hyena_filter_cls": "implicit_complex_modal",
  "pos_emb": "rotary",
  "rotary_pct": 1,
  "prenorm": true,
  "postnorm": false,
  "pre_mlp_norm": true,  
  "outer_mlp_norm": false,
  "no_weight_tying": false,
  "gpt_j_residual": false,
  "normalize_hyena_filters": false,
  "short-conv-L": 3, 
  "hyena_filter_fast_decay": 0.3,
  "hyena_filter_slow_decay": 1.2,
  "hyena_filter_w": 10, 
  "hyena_filter_order": 16,
  "hyena_filter_wd": 0.,
  # "proj_groups": 8,
  "norm": "rmsnorm",
  # "grouped_attention": true, 
  "use_fast_heads": false,
  "use_slow_heads": false,
  "use-hyena-filter": true,
  "output_layer_parallelism": "column",
  "bias_dropout_fusion": false,
  "rms_norm_epsilon": 1.0e-6,
  "identity_mlp": false,
  "mlp_type": "llama",
   "scaled-upper-triang-masked-softmax-fusion": true,
   "bias-gelu-fusion": false,
   "init_method": "small_init",
   "output_layer_init_method": "wang_init",
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 3.0e-04,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8,
     }
   },
    "deepspeed_extra_args": {
      "data_types": 
        { "grad_accum_dtype": "fp32"},
        "load_universal_checkpoint": False,
    },
   "min_lr": 3.0e-05,
   "zero_optimization": {
    "stage": 0,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
    "cpu_offload": false
  },
   "train_micro_batch_size_per_gpu": 2,
   "gradient_accumulation_steps": 16,
   "data-impl": "mmap",
   "checkpoint-activations": true,
   "checkpoint-num-layers": 2,
   "partition-activations": true,
   "synchronize-each-layer": true,
   "gradient_clipping": 1.0,
   "weight-decay": 0.1,
   "hidden-dropout": 0.0,
   "attention-dropout": 0.0,
   "precision": "bfloat16",
   "bf16": {
   "enabled": true
    }, 
   "train-iters": 120_000,
   "lr-decay-iters": 120_000,
   "distributed-backend": "nccl",
   "lr-decay-style": "cosine",
   "warmup": 0.0,  # this was changed for finetuning
   "checkpoint-factor": 500,
   "extra_save_iters": [4],
   "eval-interval": 100,
   "eval-iters": 20,
   "log-interval": 10,
   "steps_per_print": 10,
   "keep-last-n-checkpoints": 5,
   "wall_clock_breakdown": false,
  # "save": "/checkpoint/etnguyen/7b_striped_120k",
  "save": "/checkpoint/hielab/etnguyen/checkpoints/evo2/7b_striped", # change this
  "tokenizer_type": CharLevelTokenizer,
  "master_port": 29502,
  # multinode
  "launcher": "pdsh",
  "hostfile": "./hostfile_eric",
  "deepspeed_slurm": false,
  # # resume
  # "iteration": 112000,
  # "load": "/checkpoint/etnguyen/7b_striped_120k",
  # "use_checkpoint_lr_scheduler": True,
  # finetune
  # "finetune": True,
  # "override_lr_scheduler": True,
  # "vocab_size": 512,
}
